name: Test

on:
  pull_request: {}
  push:
    branches: [main, develop]

# Enrich gradle.properties for CI/CD
env:
  CI_GRADLE_ARG_PROPERTIES: >
    -Porg.gradle.jvmargs=-Xmx2g
    -Porg.gradle.parallel=false

jobs:
  tests:
    name: Runs all tests
    runs-on: macos-latest # for the emulator
    # Allow all jobs on main and develop. Just one per PR.
    concurrency:
      group: ${{ github.ref == 'refs/heads/main' && format('unit-tests-main-{0}', github.sha) || github.ref == 'refs/heads/develop' && format('unit-tests-develop-{0}', github.sha) || format('unit-tests-{0}', github.ref) }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - uses: michaelkaye/setup-matrix-synapse@v1.0.3
        with:
          uploadLogs: true
          httpPort: 8080
          disableRateLimiting: true
          public_baseurl: "http://10.0.2.2:8080/"
      - name: Run all the codecoverage tests at once
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86
          profile: Nexus 5X
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          emulator-build: 7425822
          script: ./gradlew theCodeCoverageReport --stacktrace -i $CI_GRADLE_ARG_PROPERTIES

      - name: Upload Codecov data
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: codecov-xml
          path: |
            build/reports/jacoco/theCodeCoverageReport/theCodeCoverageReport.xml
      - name: Format unit test results
        if: always()
        run: python3 ./tools/ci/render_test_output.py unit ./**/build/test-results/**/*.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always() &&
          github.event.sender.login != 'dependabot[bot]' &&
          ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository )
        with:
          files: ./**/build/test-results/**/*.xml

  sonarqube:
    name: Sonarqube upload
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/download-artifact@v3
        with:
          name: codecov-xml # will restore to theCodeCoverageReport.xml by default; we restore to the same location in following tasks
      - run: mkdir -p build/reports/jacoco/theCodeCoverageReport/
      - run: mv theCodeCoverageReport.xml build/reports/jacoco/theCodeCoverageReport/
      - run: ./gradlew sonarqube $CI_GRADLE_ARG_PROPERTIES
        env:
          ORG_GRADLE_PROJECT_SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
