name: Test

on:
  pull_request: {}
  push:
    branches: [main, develop]

# Enrich gradle.properties for CI/CD
env:
  CI_GRADLE_ARG_PROPERTIES: >
    -Porg.gradle.jvmargs=-Xmx2g
    -Porg.gradle.parallel=false

jobs:
  ## XXX THIS IS DEMO QUALITY ONLY
 
  unit-tests:
    name: Run Unit Tests
    runs-on: macos-latest # for the emulator
    # Allow all jobs on main and develop. Just one per PR.
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - uses: michaelkaye/setup-matrix-synapse@v1.0.3
        with:
          uploadLogs: true
          httpPort: 8080
          disableRateLimiting: true
          public_baseurl: "http://10.0.2.2:8080/"
      - name: Run all the codecoverage tests at once
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86
          profile: Nexus 5X
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          emulator-build: 7425822
          script: ./gradlew theCodeCoverageReport --stacktrace -i $CI_GRADLE_ARG_PROPERTIES

